let shopItemsData = [
  {
    id: "ytfdjgcm",
    name: "Books",
    price: 9.99,
    desc: "Books include: <br> - harry potter 1<br> - harry potter 2<br> - harry potter 3<br> - harry potter 4<br> - harry potter 5",
    img: "images/desktop.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Pencils",
    price: 0.99,
    desc: "state of the art pencils made from the finest woods.",
    img: "images/laptop11.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Backpacks",
    price: 24.99,
    desc: "Durable, ergonomic backpacks available in various sizes and designs for students of all ages.",
    img: "images/monitor.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "laptops",
    price: 299.99,
    desc: "Lightweight and powerful laptops suitable for online learning, assignments, and research.",
    img: "images/gaming_bundle.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Scientific Calculators",
    price: 14.99,
    desc: "Advanced scientific calculators for high school and college students, featuring graphing capabilities.",
    img: "images/ram.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Notebooks and Journals",
    price: 4.99,
    desc: "High-quality, lined, dotted, and plain notebooks and journals for taking notes and organizing thoughts.",
    img: "images/motherboard.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Stationery Sets",
    price: 9.99,
    desc: "Comprehensive stationery sets including pens, pencils, erasers, rulers, and highlighters.",
    img: "images/harddrive.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Desk Organizers",
    price: 14.99,
    desc: "Multifunctional desk organizers to keep stationery and school supplies neatly arranged.",
    img: "images/ssd.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Lunch Boxes",
    price: 9.99,
    desc: "insulated lunch boxes and bags to keep meals fresh and organized throughout the school day.",
    img: "images/case.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Whiteboards and Markers",
    price: 14.99,
    desc: "Personal whiteboards and sets of dry-erase markers for home study spaces or dorm rooms.",
    img: "images/desktop_computer.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Graphing Paper",
    price: 4.99,
    desc: "Pads of graphing paper ideal for math, science, and engineering assignments.",
    img: "images/gaming_laptop.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Noise-Cancelling Headphones",
    price: 49.99,
    desc: "High-quality noise-cancelling headphones to help students focus in noisy environments.",
    img: "images/graphics_card.jpg",
  },
];
