let shopItemsData = [
  {
    id: "ytfdjgcm",
    name: "Desktop Computers",
    price: 319.99,
    desc: "Brand new minted edition state of the art computer set. <br> Includes: <br> - State of the art derek style monitor <br> - Keyboard <br> - Mouse with a dell OS.",
    img: "images/desktop.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Laptops",
    price: 199.99,
    desc: "- Intel i7 or i9 processor <br> - Windows 10 or 11 <br> - 16 - 32 GB of RAM <br> - Dedicated video processor should be one of the following or greater: Nvidia Quadro, Nvidia Derek, Nvidia® Geforce 1660, 2060, 3060 or greater. <br> - At least a 500 GB hard drive (SSD hard drive) <br> - Wireless networking adapter (for internet)",
    img: "images/laptop11.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Computer Monitor",
    price: 199.99,
    desc: " - 4k ultra high dereknition <br> - 75Hz refresh rate <br> - 1080 x 1920 <br> - RGB Colour pallet ",
    img: "images/monitor.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Computer Accessories",
    price: 59.99,
    desc: "- Keyboard <br> - Mouse <br> - Mouse mat <br> - Headset <br> - Headset adapter (audio and microphone > 2 separate cables)",
    img: "images/gaming_bundle.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Computer Memory",
    price: 89.99,
    desc: "- 2 GB <br> - 4 GB <br> - 8 GB <br> - 16 GB <br> - 32 GB <br> - 64 GB",
    img: "images/ram.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Motherboards & CPU's",
    price: 179.99,
    desc: "- Gigabyte Z790 Aorus Xtreme <br> - Gigabyte Z690 Aorus Pro <br> - ASRock Z690 Extreme WiFi 6E <br> - Gigabyte Z690I Aorus Ultra Plus",
    img: "images/motherboard.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Hard Drives",
    price: 69.99,
    desc: "- Seagate BarraCuda <br> - Western Digital Blue Desktop <br> - Seagate Firecuda Desktop <br> - Seagate IronWolf NAS <br> - Western Digital My Book",
    img: "images/harddrive.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "SSD's",
    price: 89.99,
    desc: "- WD My Passport. <br> - PNY CS900. <br> - SanDisk Extreme Portable. <br> - WD Black SN850.  <br> - Samsung 870 QVO ",
    img: "images/ssd.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Computing Books",
    price: 19.99,
    desc: "- Computing books <br> - Coding books related to programming languages such as JavaScript, Python, Java and HTML5 <br> - Books also on hardware and history of computing",
    img: "images/case.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "CDs",
    price: 14.99,
    desc: "- Cds related to computing <br> -CDS include readings of coding <br> - Cds also include lectures",
    img: "images/desktop_computer.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "DvDS",
    price: 19.99,
    desc: "- DvDs on Computing <br> - DvDs include lectures and pass examples on coding and computing",
    img: "images/gaming_laptop.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "rename later",
    price: 239.99,
    desc: "- i cant think of anything else to add, this spot is basically free parking <br> - i also forgot to change the jpgs but im sure its fine",
    img: "images/graphics_card.jpg",
  },
];
